name: check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v4
      - uses: https://github.com/bufbuild/buf-setup-action@v1
      - uses: https://github.com/bufbuild/buf-lint-action@v1
