name: update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: https://github.com/DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - uses: https://github.com/spotdemo4/nix-gitea-cache-action@98163dcea594ce2e8b15cac50ea80ffe0b221025 # v1.1.1

      - name: Renovate
        env:
          RENOVATE_CONFIG_FILE: .gitea/renovate-global.json
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.GH_TOKEN }}
        run: nix develop --accept-flake-config --command renovate
